@PORT=8080

### Create a form with several questions
POST http://localhost:{{PORT}}/admin/submit
Content-Type: application/json

{
  "userId": "67e0464059a0efb9ff",
  "title": "Week at work : satisfaction form",
  "questions": [
    {
      "questionText": "How do you rate your week at the office?",
      "questionType": "rating",
      "questionNumber": 1
    },
    {
      "questionText": "What are the areas you would like to improve?",
      "questionType": "text",
      "questionNumber": 2
    }
    // Add more questions if needed ...
  ]
}

### Get previously created form
### Reminder => replace :formId by value before running
GET http://localhost:{{PORT}}/user/form/:formId
Content-Type: application/json

### Save form responses by user
POST http://localhost:{{PORT}}/user/submit
Content-Type: application/json

{
  "userId": "654e044059a0efb9ffd41368",
  "formId": "TO_ADD_MANUALLY",
  "answers": [
    {
      "questionId": "654fda6ebc0fd35250c38426",
      "answerText": "5"
    },
    {
      "questionId": "654fda6ebc0fd35250c38427",
      "answerText": "The service can be improved"
    }
    // Add more responses if needed ...
  ]
}
### Get user responses to form
### Reminder => replace :userId and :formId by value before running
GET http://localhost:{{PORT}}/admin/userResponse/654e044059a0efb9ffd41368/:formId 
