version: '3'
services:
  form-api-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'afrezefond/form-api-test:latest'
    container_name: form-api-test
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongodb:27017
    ports:
      - '8080:8080'
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
